import assert from 'node:assert/strict';
import fs from 'node:fs';
import {aimScore,rewardTraining} from './src/game/training.ts';
assert.equal(aimScore(0,0),0);assert.equal(aimScore(30,0),100);assert.ok(aimScore(1,0)<4);assert.ok(aimScore(30,30)<100);
const state={players:[{id:'a',alias:'A',agent:'jett',agentMastery:{jett:48}},{id:'b',alias:'B',agent:'sage',agentMastery:{sage:99}}],mapMastery:{Ascent:48}};
const result={id:'one',kind:'aim',score:100,targets:[{playerId:'a',agentId:'jett'}],map:'Ascent',completedAt:'today'};
rewardTraining(state,result);assert.equal(state.players[0].agentMastery.jett,56);assert.equal(state.players[1].agentMastery.sage,99);
rewardTraining(state,result);assert.equal(state.players[0].agentMastery.jett,56);assert.equal(state.trainingHistory.length,1);
rewardTraining(state,{...result,id:'two',targets:[{playerId:'b',agentId:'sage'}]});assert.equal(state.players[1].agentMastery.sage,100);
rewardTraining(state,{...result,id:'zero',score:0});assert.equal(state.players[0].agentMastery.jett,56);
rewardTraining(state,{...result,id:'map',kind:'map-guess'});assert.equal(state.players[0].mapMastery.Ascent,56);assert.equal(state.players[1].mapMastery.Ascent,48);assert.equal(state.mapMastery.Ascent,52);
rewardTraining(state,{...result,id:'snapshot',targets:[{playerId:'a',agentId:'omen'}]});assert.equal(state.players[0].agentMastery.omen,56);assert.equal(state.players[0].agentMastery.jett,56);
const abilities=JSON.parse(fs.readFileSync('abilities.json','utf8'));assert.equal(abilities.length,116);for(const a of abilities)assert.ok(fs.existsSync(`public${a.icon}`));
console.log('Training scoring, saved rewards, caps, selection and ability assets OK');
const {beginTraining,trainingUsed,trainingBlock,timedScore}=await import('./src/game/training.ts');
const budget={week:1,money:500,players:[{id:'a'},{id:'b'}]};
assert.equal(beginTraining(budget,['a','a','b']),true);assert.equal(budget.money,420);assert.equal(trainingUsed(budget,'a'),1);
beginTraining(budget,['a']);beginTraining(budget,['a']);assert.equal(beginTraining(budget,['a','b']),false);assert.equal(trainingUsed(budget,'b'),1);assert.equal(budget.money,340);
budget.week=2;assert.equal(trainingUsed(budget,'a'),0);assert.equal(beginTraining(budget,['a']),true);
budget.money=0;assert.ok(trainingBlock(budget,['b']));assert.equal(beginTraining(budget,['b']),false);
assert.ok(timedScore(100,10000,120000)>timedScore(100,60000,120000));assert.equal(timedScore(0,1,120000),0);assert.ok(timedScore(50,1000,120000)<timedScore(100,1000,120000));
