import {test,expect} from '@playwright/test';

test('home connects onboarding, career actions, navigation and mobile layout',async({page})=>{
  const errors:string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto('/');
  await expect(page.locator('#home-title')).toHaveText('VAVAMANAGER');
  await expect(page.locator('.home-shortcut')).toHaveCount(4);
  await expect(page.locator('.home-widget')).toHaveCount(4);
  await page.screenshot({path:'test-results/home-initial-desktop.png',fullPage:true});
  await page.locator('.home-continue').click();
  await page.locator('#select-team').click();
  await page.locator('#manager-name').fill('Pedro');
  await page.locator('#start').click();
  await page.locator('[data-contract-sign]').click();
  await expect(page.locator('.home-profile b')).toHaveText('Pedro');
  await expect(page.locator('.home-continue')).toContainText('VER CONVITE');
  await page.locator('.home-continue').click();
  await page.locator('[data-action="accept-invite"]').click();
  await page.locator('.home-nav-link[data-view="overview"]').click();
  await expect(page.locator('.home-matchup')).toBeVisible();
  await expect(page.locator('.home-continue')).toContainText('CONTINUAR');
  await page.locator('.home-continue').click();
  await expect(page.locator('.home-career-status')).toContainText('DIA 2 / 7');
  await page.locator('[data-action="open-calendar"]').click();
  await expect(page.locator('.team-calendar-dialog')).toBeVisible();
  await page.locator('[data-close-calendar]').click();
  await page.screenshot({path:'test-results/home-career-desktop.png',fullPage:true});
  await page.locator('.home-card-team').click();
  await expect(page.locator('.lineup-panel')).toBeVisible();
  await page.locator('summary[aria-label="Mais opções de Equipe"]').click();
  await page.locator('.home-nav-menu [data-view="training"]').click();
  await expect(page.locator('#lab-map')).toBeVisible();
  await page.locator('.home-nav-link[data-view="overview"]').click();
  await page.locator('.home-news-story').click();
  await expect(page.locator('.home-news-dialog')).toBeVisible();
  await page.locator('.home-news-dialog button').click();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/home-career-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.locator('.home-icon-button[data-view="settings"]').click();
  await page.locator('[data-action="main-menu"]').click();
  await expect(page.locator('.home-profile b')).toHaveText('Pedro');
  await page.locator('.home-continue').click();
  await page.locator('[data-action="open-simulation"]').click();
  await page.locator('[data-action="advance-week"]').click();
  await expect(page.locator('.home-continue')).toContainText('DIA DE PARTIDA');
  await expect(page.locator('.home-career-status')).toContainText('DIA 7 / 7');
  await page.locator('[data-close-simulation]').click();
  await page.locator('.home-continue').click();
  await expect(page.locator('[data-action="watch"]')).toBeEnabled();
  expect(errors).toEqual([]);
});
