import type {CareerState} from '../types/career.ts';
import {academyGrowthInterval,academyPromotionMinimum,academyScoutingCost,academyTrainingCost,academyUpgradeCost} from '../game/academy.ts';
import {genericPortrait} from './portraits.ts';
import {academyTrainingGain,shopBonuses} from '../game/shop.ts';

export function academyView(state:CareerState,cash:(value:number)=>string,escape:(value:unknown)=>string):string {
  const prospects=state.academyProspects||[],level=state.academyLevel||1,nextCost=academyUpgradeCost(level);
  const interval=academyGrowthInterval(level);
  const upgrade=Number.isFinite(nextCost)?`<button class="primary" data-action="upgrade-academy" ${state.money<nextCost?'disabled':''}>MELHORAR ESTRUTURA · ${cash(nextCost)} ↗</button>`:'<span class="academy-max-level">NÍVEL MÁXIMO</span>';
  const cards=prospects.map(prospect=>{
    const progress=Math.round(prospect.rating/prospect.potential*100),ready=prospect.rating>=academyPromotionMinimum;
    const trained=prospect.lastTrainingWeek===state.week;
    return `<article class="academy-prospect"><div class="academy-prospect-top"><span class="academy-avatar">${genericPortrait(prospect.name,prospect.portrait)}</span><div><span class="academy-role">${escape(prospect.role)}</span><h3>${escape(prospect.name)}</h3><small>${prospect.age} anos · ${prospect.weeksInAcademy} semanas na base</small></div><b class="academy-rating">${prospect.rating}<small>OVR</small></b></div><div class="academy-stats"><span>OVERALL ATUAL <b>${prospect.rating}</b></span><span>POTENCIAL <b>${prospect.potential}</b></span></div><div class="academy-progress"><span style="width:${progress}%"></span></div><div class="academy-projection">${ready?'Pronto para o elenco principal':`Faltam ${academyPromotionMinimum-prospect.rating} pontos para poder subir`}</div><div class="academy-actions"><button data-action="train-prospect" data-id="${prospect.id}" ${trained||prospect.rating>=prospect.potential||state.money<academyTrainingCost?'disabled':''}>${trained?'TREINO FEITO NESTA SEMANA':`TREINAR · ${cash(academyTrainingCost)}`}</button><button class="academy-promote" data-action="promote-prospect" data-id="${prospect.id}" ${!ready?'disabled':''}>${ready?'PROMOVER AO ELENCO':'AINDA EM DESENVOLVIMENTO'}</button></div></article>`;
  }).join('');
  return `<div class="page-title"><div><small class="eyebrow">FORMAÇÃO DE TALENTOS</small><h1>TACTICAL <em>ACADEMY.</em></h1><p>Desenvolva jovens promessas dentro da estrutura do clube e decida quando promovê-las.</p></div><div class="overall-box"><small>JOVENS NA BASE</small><b>${prospects.length}<span> / 6</span></b></div></div><section class="academy-facility"><div class="academy-facility-mark">A<span>+</span></div><div class="academy-facility-copy"><small class="eyebrow">CENTRO DE DESENVOLVIMENTO</small><h2>Base do ${escape(state.team.toUpperCase())}</h2><p>Nível ${level} · evolução passiva a cada ${interval} ${interval===1?'semana':'semanas'} · treino individual para acelerar um prospect.</p><div class="academy-levels">${[1,2,3].map(value=>`<span class="${level>=value?'active':''}">${String(value).padStart(2,'0')}</span>`).join('')}</div></div><div class="academy-upgrade">${upgrade}</div></section><div class="academy-section-head"><div><small class="eyebrow">GERAÇÃO ATUAL</small><h2>Jovens promessas</h2></div><button class="academy-discover" data-action="discover-prospect" ${prospects.length>=6||state.money<academyScoutingCost?'disabled':''}>OBSERVAR PROMESSA · ${cash(academyScoutingCost)}</button></div>${shopBonuses(state).academyTraining?`<p class="shop-equipment-note">Estações da Academy instaladas: até +${academyTrainingGain(state)} de overall por treino individual.</p>`:''}<div class="academy-grid">${cards||'<section class="academy-empty">Nenhum jovem na base no momento.</section>'}</div><p class="academy-footnote">Os atletas e seus potenciais são gerados para esta carreira. O desenvolvimento e os valores são simulações do jogo.</p>`;
}
