import type {CareerState,ManagerEmail} from '../types/career.ts';

export type MailFolder='all'|ManagerEmail['category'];
const folders:{id:MailFolder;label:string;icon:string}[]=[
  {id:'all',label:'Caixa de entrada',icon:'inbox'}, {id:'general',label:'Diretoria',icon:'building'},
  {id:'player',label:'Elenco',icon:'users'}, {id:'sponsor',label:'Patrocínios',icon:'briefcase'},
  {id:'transfer',label:'Transferências',icon:'arrows'}, {id:'streamer',label:'Streamers',icon:'video'},
];
function icon(name:string):string{
  const paths:Record<string,string>={
    mail:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 6 9 7 9-7"/>',
    inbox:'<path d="m3 12 3-8h12l3 8v8H3v-8Z"/><path d="M3 12h5l2 3h4l2-3h5"/>',
    building:'<path d="M6 21V3h12v18M3 21h18M9 7h1m4 0h1M9 11h1m4 0h1M9 15h1m4 0h1m-4 6v-3h2v3"/>',
    users:'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2m1-15a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 4v2"/>',
    briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12q9 5 18 0m-9 0v4"/>',
    arrows:'<path d="M4 7h16m-4-4 4 4-4 4M20 17H4m4-4-4 4 4 4"/>',
    video:'<rect x="3" y="5" width="13" height="14" rx="2"/><path d="m16 10 5-3v10l-5-3"/>',
    search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
    check:'<path d="m4 12 5 5L20 6"/>',back:'<path d="m10 5-7 7 7 7M3 12h18"/>',
    external:'<path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/>',
  };
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.mail}</svg>`;
}
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
export function filterMailMessages(state:CareerState,folder:MailFolder,query=''):ManagerEmail[]{
  const search=normalize(query.trim());
  return (state.emails||[]).filter(email=>(folder==='all'||email.category===folder)&&(!search||normalize(`${email.from} ${email.subject} ${email.preview} ${email.body}`).includes(search)));
}

export function mailView(state:CareerState,escape:(value:unknown)=>string,cash:(value:number)=>string,folder:MailFolder,selectedId:string|null,query='',readingOpen=false):string{
  const all=state.emails||[],visible=filterMailMessages(state,folder,query);
  const selected=visible.find(email=>email.id===selectedId)||visible[0];
  const unread=all.filter(email=>!email.read).length;
  const folderLabel=folders.find(item=>item.id===folder)?.label||'Caixa de entrada';
  const avatar=(email:ManagerEmail)=>`<span class="mail-avatar mail-${email.category}">${escape(email.from.trim().split(/\s+/).filter(word=>word!=='·').slice(0,2).map(word=>word[0]).join('').toUpperCase())}</span>`;
  const list=visible.map(email=>`<button type="button" class="mail-row ${selected?.id===email.id?'selected':''} ${email.read?'':'unread'}" data-mail-id="${escape(email.id)}" aria-current="${selected?.id===email.id?'true':'false'}">${avatar(email)}<span class="mail-row-copy"><span class="mail-row-sender"><b>${escape(email.from)}</b><time>Sem. ${String(email.week).padStart(2,'0')}</time></span><strong>${escape(email.subject)}</strong><small>${escape(email.preview)}</small><span class="mail-row-label">${folders.find(item=>item.id===email.category)?.label||'Mensagem'}${!email.read?'<i aria-label="Não lida"></i>':''}</span></span></button>`).join('');
  const category=folders.find(item=>item.id===selected?.category)?.label;
  const detail=selected?`<article class="mail-reading"><div class="mail-reading-top"><button type="button" class="mail-mobile-back" data-mail-back>${icon('back')}<span>Caixa de entrada</span></button><span class="mail-category mail-${selected.category}">${category}</span><time>Temporada 2026 · Semana ${selected.week}</time></div><h2>${escape(selected.subject)}</h2><div class="mail-sender">${avatar(selected)}<div><div class="mail-sender-line"><b>${escape(selected.from)}</b><span>&lt;${escape(selected.address)}&gt;</span></div><small>Para: <strong>${escape(state.manager)}</strong> &lt;manager@${escape(state.team)}.vava.game&gt;</small></div></div><div class="mail-body">${selected.body.split(/\n\s*\n/).map(paragraph=>`<p>${escape(paragraph).replace(/\n/g,'<br>')}</p>`).join('')}</div>${selected.offer?.status==='pending'?`<section class="mail-offer"><span class="mail-offer-icon">${icon('arrows')}</span><div><small>PROPOSTA DE TRANSFERÊNCIA</small><b>${cash(selected.offer.fee)}</b><p>A diretoria aguarda sua decisão sobre a venda do atleta.</p><div class="mail-offer-actions"><button type="button" class="primary" data-action="accept-transfer" data-id="${escape(selected.id)}">Aceitar proposta</button><button type="button" class="mail-decline" data-action="reject-transfer" data-id="${escape(selected.id)}">Recusar</button></div></div></section>`:selected.offer?`<div class="mail-offer-result">${icon('check')}Proposta ${selected.offer.status==='accepted'?'aceita':'recusada'}</div>`:''}${selected.category==='sponsor'||selected.category==='streamer'?`<button type="button" class="mail-link" data-view="sponsors">${selected.category==='sponsor'?'Ver patrocínios':'Ver campanha de marketing'}${icon('external')}</button>`:selected.category==='transfer'?`<button type="button" class="mail-link" data-view="market">Abrir transferências${icon('external')}</button>`:selected.category==='player'?`<button type="button" class="mail-link" data-view="squad">Gerenciar elenco${icon('external')}</button>`:''}<footer class="mail-message-footer">Comunicação interna do clube · VAVA Mail</footer></article>`:`<div class="mail-empty">${icon('mail')}<b>${query?'Nenhum resultado encontrado':'Sua caixa está em dia'}</b><p>${query?'Tente outro nome ou assunto na busca.':'As novidades da carreira aparecerão aqui.'}</p></div>`;
  return `<div class="mail-page-title"><div><small class="eyebrow">COMUNICAÇÃO DO CLUBE</small><h1>Seu <em>email.</em></h1></div><span class="mail-status"><i></i>${unread?`${unread} ${unread===1?'mensagem não lida':'mensagens não lidas'}`:'Tudo em dia'}</span></div><section class="mail-shell ${readingOpen?'is-reading':''}" aria-label="Email do clube"><aside class="mail-sidebar"><div class="mail-app-brand"><span>${icon('mail')}</span><div><b>VAVA Mail</b><small>Seu clube. Sua rede.</small></div></div><span class="mail-caption">CAIXA DE EMAIL</span><nav aria-label="Pastas de email">${folders.map(item=>{const count=all.filter(email=>!email.read&&(item.id==='all'||email.category===item.id)).length;return `<button type="button" class="mail-folder ${folder===item.id?'active':''}" data-mail-folder="${item.id}" aria-label="${item.label}${count?`, ${count} não lidas`:''}" aria-current="${folder===item.id?'page':'false'}">${icon(item.icon)}<span>${item.label}</span>${count?`<i>${count}</i>`:''}</button>`}).join('')}</nav><div class="mail-sidebar-foot"><span class="mail-account-avatar">${escape(state.manager.slice(0,1).toUpperCase())}</span><div><b>${escape(state.manager)}</b><small>manager@${escape(state.team)}.vava.game</small></div><i title="Conectado"></i></div></aside><div class="mail-workspace"><header class="mail-toolbar"><label class="mail-search">${icon('search')}<input id="mail-search" type="search" autocomplete="off" placeholder="Buscar remetente ou assunto" aria-label="Buscar emails" value="${escape(query)}"/></label><button type="button" class="mail-read-all" data-mail-read-all aria-label="Marcar mensagens desta pasta como lidas" title="Marcar mensagens desta pasta como lidas" ${visible.some(email=>!email.read)?'':'disabled'}>${icon('check')}<span>Marcar como lidas</span></button></header><div class="mail-columns"><section class="mail-inbox" aria-label="Lista de emails"><header class="mail-inbox-head"><div><h2>${folderLabel}</h2><small>${visible.length} ${visible.length===1?'mensagem':'mensagens'}${query?' encontradas':''}</small></div><span>${visible.length}</span></header><div class="mail-list">${list||`<div class="mail-list-empty">${icon('inbox')}<b>${query?'Nenhum resultado':'Sem mensagens'}</b><small>${query?'Tente buscar outro assunto.':'Novos contatos aparecerão aqui.'}</small></div>`}</div></section><section class="mail-content" aria-label="Leitura de email">${detail}</section></div></div></section>`;
}
