import type {CombatEvent, MatchPlayer, MatchWeapon, WatchOptions} from '../types/game.ts';

export function weaponIcon(weapon:MatchWeapon='vandal') {
  const paths:Record<MatchWeapon,string>={
    vandal:'M2 18h12l8-8h32v-3h6v3h24v4h-24l-6 5-1 7-7-2 2-7H34l-4 10-8-3 3-9-8 8H2z',
    phantom:'M2 16h17l7-6h35v-3h5v3h18v5H59l-5 4-1 7-7-2 2-6H34l-4 9-8-3 3-9-9 7H2z',
    operator:'M2 19h13l8-7h26V9H36V5h24v4h-6v3h30v3H55l-5 6-1 7-6-2 1-8H33l-7 7-8-4-8 5H2z',
    classic:'M22 8h42v12H47l-7 11H29l4-17H22zm25 13h9v4h-9z',
  };
  return `<svg class="broadcast-weapon" viewBox="0 0 86 36" role="img" aria-label="${weapon}"><path fill="currentColor" d="${paths[weapon]}"/></svg>`;
}

export const headshotIcon='<svg class="broadcast-headshot" viewBox="0 0 24 24" role="img" aria-label="Headshot"><path fill="currentColor" d="M12 2a7 7 0 0 0-7 7v5h3v5h8v-5h3V9a7 7 0 0 0-7-7m-3 7h2v3H9zm4 0h2v3h-2z"/><path fill="none" stroke="currentColor" d="M0 12h5m14 0h5M12 0v4m0 16v4"/></svg>';
export const objectiveIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2 21 9l-3 10H6L3 9zm0 4-5 4 2 6h6l2-6z" fill="currentColor"/></svg>';

export function killFeedRow(event:CombatEvent,players:MatchPlayer[],escape:WatchOptions['escape']) {
  const killer=players[event.killer],victim=players[event.victim],helper=event.assist!==null?players[event.assist]:null;
  const portrait=(p:MatchPlayer,kind:string)=>`<img class="kill-${kind}-portrait" src="/assets/agents/${encodeURIComponent(p.agent)}.png" alt="${escape(p.agent)}">`;
  return `<div class="broadcast-kill side-${event.killer<5?0:1}" aria-label="${escape(killer.alias)} eliminou ${escape(victim.alias)}${helper?`, assistência de ${escape(helper.alias)}`:''}${event.headshot?', headshot':''}"><span class="kill-attacker">${portrait(killer,'main')}<b>${escape(killer.alias)}</b>${helper?`<span class="kill-assist" title="Assistência de ${escape(helper.alias)}"><span>+</span>${portrait(helper,'assist')}<small>${escape(helper.alias)}</small></span>`:''}</span><span class="kill-method">${weaponIcon(event.weapon)}${event.headshot?headshotIcon:''}</span><span class="kill-victim"><b>${escape(victim.alias)}</b>${portrait(victim,'main')}</span></div>`;
}

export function broadcastLayout(options:WatchOptions) {
  const {players,own,opponent,escape:esc,ownLogo,opponentLogo}=options;
  const badge=(name:string,logo?:string)=>logo?`<img src="${esc(logo)}" alt="" class="broadcast-team-logo">`:`<span class="broadcast-team-monogram" aria-hidden="true">${esc(name.slice(0,2))}</span>`;
  const roster=(side:0|1)=>`<section class="broadcast-roster side-${side}" aria-label="Elenco ${esc(side===0?own:opponent)}"><header>${badge(side===0?own:opponent,side===0?ownLogo:opponentLogo)}<b>${esc(side===0?own:opponent)}</b><span class="broadcast-alive" data-alive="${side}">5 VIVOS</span></header><div class="sim-roster">${players.slice(side*5,side*5+5).map((p,index)=>`<button class="side-${side}" data-roster="${side*5+index}" aria-pressed="false" aria-label="Acompanhar ${esc(p.alias)}"><img class="broadcast-player-portrait" src="/assets/agents/${encodeURIComponent(p.agent)}.png" alt="${esc(p.agent)}"><span class="broadcast-player-info"><span class="broadcast-player-name">${esc(p.alias)}</span><span class="broadcast-health"><i></i></span><span class="broadcast-player-bottom"><small class="broadcast-hp">♥ 100</small><span class="broadcast-loadout">${weaponIcon('classic')}</span></span></span><span class="broadcast-player-numbers"><b class="sim-player-stats" aria-label="Abates, assistências, mortes">0 / 0 / 0</b><small>K / A / D</small></span></button>`).join('')}</div></section>`;
  return `<section class="match-viewer broadcast-viewer" role="dialog" aria-modal="true" aria-label="Simulação da partida" tabindex="-1">
    <header class="broadcast-header"><div class="broadcast-competition">${objectiveIcon}<div><b>${esc(options.competition||'VCT · BO3')}</b><small>${esc(options.stage||'TRANSMISSÃO AO VIVO')}</small></div></div><div class="broadcast-scoreboard"><div class="broadcast-team side-0"><b>${esc(own)}</b>${badge(own,ownLogo)}<strong class="broadcast-own-score">0</strong></div><div class="broadcast-round"><small class="broadcast-round-number">ROUND 1</small><strong class="broadcast-clock">—</strong><span class="broadcast-side">ATAQUE</span></div><div class="broadcast-team side-1"><strong class="broadcast-opponent-score">0</strong>${badge(opponent,opponentLogo)}<b>${esc(opponent)}</b></div></div><div class="broadcast-map-info"><span><small>MAPA</small><b class="broadcast-map-name">—</b></span><img class="broadcast-map-preview" alt=""><button class="sim-finish" aria-label="Pular simulação e ver resultado">PULAR ↗</button></div></header>
    <div class="broadcast-body"><aside class="broadcast-left"><div class="sim-minimap"><div class="sim-minimap-plan"><img alt="Planta do mapa para orientação">${players.map((_,id)=>`<i class="side-${id<5?0:1}" data-mini-unit="${id}"></i>`).join('')}</div><small class="sim-minimap-name"></small></div>${roster(0)}</aside>
    <main class="broadcast-arena"><div class="sim-map"><div class="sim-canvas" role="img" aria-label="Arena 3D animada. Arraste para girar a câmera ou selecione um atleta no elenco."></div><div class="sim-plan-view" hidden><img alt="Visão tática 2D do mapa">${players.map((p,id)=>`<button class="side-${id<5?0:1}" data-plan-unit="${id}" aria-label="Acompanhar ${esc(p.alias)}"><img src="/assets/agents/${encodeURIComponent(p.agent)}.png" alt=""><span>${esc(p.alias)}</span></button>`).join('')}<i class="sim-plan-spike">◆</i></div><div class="sim-killfeed" role="log" aria-label="Abates e assistências" aria-live="polite"></div><div class="sim-player-card" hidden><img alt=""><div><small class="sim-player-state"></small><b class="sim-player-name"></b><span class="sim-player-agent"></span></div></div><div class="sim-reticle" aria-hidden="true"><i></i><i></i></div><div class="sim-round-banner"></div></div>
    <div class="broadcast-playback"><button class="sim-pause" aria-label="Pausar ou continuar replay">PAUSAR</button><label>VELOCIDADE <select class="sim-speed" aria-label="Velocidade do replay"><option value="0.5">0,5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option></select></label><button class="sim-audio" aria-pressed="false">SOM: DESLIGADO</button><label>VISÃO <select class="sim-view-mode" aria-label="Visão da partida"><option value="3d">3D</option><option value="2d">2D</option></select></label></div>
    <details class="broadcast-camera"><summary>CÂMERA <span class="sim-camera-label">TÁTICA 3D</span></summary><div class="sim-camera-tools"><label>CÂMERA <select class="sim-camera-mode" aria-label="Modo da câmera"><option value="tactical">Tática 3D</option><option value="follow">Terceira pessoa</option><option value="player">Visão do atleta</option></select></label><div class="sim-player-switch"><button class="sim-player-prev" aria-label="Atleta vivo anterior">‹</button><button class="sim-player-next" aria-label="Próximo atleta vivo">›</button></div><div class="sim-camera-orbit"><button class="sim-rotate-left" aria-label="Girar câmera para a esquerda">↶</button><button class="sim-rotate-right" aria-label="Girar câmera para a direita">↷</button></div><button class="sim-camera-reset" aria-label="Mostrar mapa inteiro">MAPA INTEIRO</button><label>ZOOM <input class="sim-zoom" type="range" min="1" max="3" step="0.1" value="1" aria-label="Zoom da câmera"></label></div></details>
    <div class="broadcast-rounds" aria-label="Histórico dos rounds"></div></main><aside class="broadcast-right">${roster(1)}<section class="broadcast-events"><header><h3>EVENTOS</h3><button class="sim-event-filter" aria-pressed="false">Ver todos</button></header><div class="sim-feed" role="log" aria-label="Eventos da rodada"><p class="broadcast-event-empty">Aguardando os primeiros eventos.</p></div></section></aside></div>
    <div class="sim-objective"><span class="objective-dot"></span><div><small>OBJETIVO DO ROUND</small><b class="spike-status">CONTROLE DO MAPA</b></div><strong class="spike-clock">—</strong><div class="spike-progress"><i></i></div></div><footer class="broadcast-footer"><span class="sim-status" aria-live="polite">CARREGANDO ARENA 3D…</span><span class="sim-score"></span><small>Selecione um atleta para acompanhar · Esc pausa o replay</small></footer>
  </section>`;
}
