import type {CareerState} from '../types/career.ts';
import {careerProgression} from '../game/progression.ts';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function progressionView(state:CareerState){
  const progress=careerProgression(state);
  const budget=state.money.toLocaleString('pt-BR');
  const average=Math.round(state.players.slice(0,5).reduce((sum,player)=>sum+player.rating,0)/5);
  return `<section class="career-guide" aria-label="Objetivos da carreira"><header><div><small>${state.demo?'DEMO · MINI TEMPORADA':'SEU PLANO DE CARREIRA'}</small><h2>${progress.finished?'Sua demo está concluída':esc(progress.current.title)}</h2></div><b>${progress.played} / ${progress.total} partidas</b></header><p>${progress.finished?'Você concluiu as quatro rodadas. Vitórias e derrotas fazem parte da campanha. Continue explorando os menus e consulte suas estatísticas.':esc(progress.current.description)}</p>${state.demo?`<ol class="career-chapters">${progress.stages.map((stage,index)=>`<li class="${index+1<state.week||progress.finished?'done':index+1===state.week?'current':''}"><small>SEMANA ${index+1}</small><b>${esc(stage.title)}</b></li>`).join('')}</ol>`:''}<div class="career-guide-actions">${progress.finished?'<button class="primary" data-view="ranking">VER BALANÇO DA DEMO →</button><button class="watch-match" data-action="export-demo-feedback">EXPORTAR FEEDBACK</button>':`<button class="primary" data-view="${progress.recommended.view}">${esc(progress.recommended.title).toUpperCase()} →</button><button class="watch-match" data-view="competition">VER PRÓXIMA PARTIDA</button>`}</div><details><summary>Entenda sua progressão</summary><p>Complete as partidas para avançar. As tarefas abaixo são sugestões: você pode explorar todos os menus e jogar com suas próprias decisões.</p><div class="career-goals">${progress.goals.map(goal=>`<button data-view="${goal.view}"><span aria-hidden="true">${goal.done?'✓':'○'}</span><span><b>${esc(goal.title)}</b><small>${esc(goal.why)}</small></span></button>`).join('')}</div>${state.demo&&!state.demo.lineupConfirmed?'<button class="watch-match" data-action="confirm-demo-lineup">CONFIRMAR MEU QUINTETO</button>':''}</details>${progress.finished?`<div class="demo-balance"><span>Campanha <b>${state.wins} vitórias · ${state.losses} derrotas</b></span><span>Elenco atual <b>${average} OVR</b></span><span>Caixa disponível <b>$ ${budget} mil</b></span><span>Evolução <b>${state.trainingHistory?.length??0} treinos · ${state.tactics.length} táticas</b></span></div><label class="demo-feedback-label">O que ficou confuso ou o que você mudaria?<textarea id="demo-feedback" rows="3" maxlength="2000" placeholder="Seu comentário será incluído no arquivo de feedback.">${esc(state.demo?.feedback??'')}</textarea></label><small>O feedback é baixado no seu dispositivo. Nenhum dado é enviado.</small>`:''}</section>`;
}
