import type { CareerState } from '../types/career.ts';
import {STREAMERS,CAMPAIGN_WEEKS} from '../game/streamer-marketing.ts';
import {BRANDS,SPONSOR_WEEKS} from '../game/brand-sponsors.ts';
import avatarImages from '../data/streamer-avatars.json';

export function sponsorsView(state:CareerState,cash:(n:number)=>string,escape:(value:unknown)=>string):string {
  const streamer=STREAMERS.find(item=>item.id===state.streamerContract?.id);
  const brand=BRANDS.find(item=>item.id===state.sponsorDeal?.id);
  const avatars:Record<string,string>=avatarImages;
  return `<div class="page-title"><div><small class="eyebrow">PARCERIAS DO CLUBE</small><h1>PATROCÍNIOS & <em>CRIADORES.</em></h1><p>Feche campanhas de marketing, receba apoio para o caixa e personalize seu clube.</p></div><div class="overall-box"><small>ORÇAMENTO</small><b class="cash-label">${cash(state.money)}</b></div></div>
  <section class="sponsor-summary" aria-label="Resumo das parcerias">
    <div><small>TORCIDA ATUAL</small><b>${state.fans.toLocaleString('pt-BR')}</b></div>
    <div><small>FÃS DAS CAMPANHAS</small><b>+${(state.marketingFans??0).toLocaleString('pt-BR')}</b></div>
    <div><small>RECEITA DOS PATROCÍNIOS</small><b>${cash(state.sponsorIncome??0)}</b></div>
    <div><small>PARCERIAS ATIVAS</small><b>${Number(!!streamer)+Number(!!brand)} / 2</b></div>
  </section>
  <section class="sponsor-section"><div class="sponsor-section-head"><div><small class="eyebrow">01 / DIVULGAÇÃO</small><h2>Streamers</h2><p>Pagamento único e novos fãs a cada semana durante ${CAMPAIGN_WEEKS} semanas.</p></div>${streamer?`<span class="sponsor-active-note">${escape(streamer.name)} · ${state.streamerContract!.weeksRemaining} semanas restantes</span>`:''}</div>
    <div class="streamer-grid">${STREAMERS.map(item=>{const active=streamer?.id===item.id,blocked=!!streamer||state.week>14||state.money<item.cost,avatar=avatars[item.id];return `<article class="streamer-card ${active?'active':''}" style="--streamer-accent:${item.accent}"><div class="streamer-head"><span class="streamer-avatar">${avatar?`<img src="${avatar}" alt="Retrato de ${escape(item.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<span class="streamer-initials" ${avatar?'style="display:none"':''} aria-hidden="true">${escape(item.name.slice(0,2).toUpperCase())}</span></span><div><small>${item.audience}</small><h2>${escape(item.name)}</h2><p>${escape(item.specialty)}</p></div>${active?'<span class="streamer-live">ATIVO</span>':''}</div><div class="streamer-benefit"><span>CAMPANHA DE ${CAMPAIGN_WEEKS} SEMANAS</span><strong>+${item.fansPerWeek.toLocaleString('pt-BR')} fãs <small>/ semana</small></strong></div><div class="streamer-contract"><span>CONTRATO <b>${cash(item.cost)}</b></span><button data-action="hire-streamer" data-id="${item.id}" ${blocked?'disabled':''}>${active?'CONTRATADO':streamer?'AGUARDE A CAMPANHA':state.week>14?'TEMPORADA ENCERRADA':state.money<item.cost?'SALDO INSUFICIENTE':'CONTRATAR ↗'}</button></div></article>`}).join('')}</div>
  </section>
  <section class="sponsor-section"><div class="sponsor-section-head"><div><small class="eyebrow">02 / APOIO FINANCEIRO</small><h2>Marcas parceiras</h2><p>Ganhe um bônus ao assinar, receita pelas próximas ${SPONSOR_WEEKS} semanas e um acessório virtual.</p></div>${brand?`<span class="sponsor-active-note">${escape(brand.name)} · ${state.sponsorDeal!.weeksRemaining} semanas restantes</span>`:''}</div>
    <div class="brand-grid">${BRANDS.map(item=>{const active=brand?.id===item.id,blocked=!!brand||state.week>14;return `<article class="brand-card ${active?'active':''}" style="--brand-accent:${item.accent}"><div class="brand-heading"><span class="brand-symbol" aria-hidden="true">${escape(item.item.icon)}</span><div><small>${escape(item.category)}</small><h3>${escape(item.name)}</h3></div>${active?'<span class="streamer-live">ATIVO</span>':''}</div><p class="brand-slogan">${escape(item.slogan)}</p><div class="brand-rewards"><span>BÔNUS <b>${cash(item.signingBonus)}</b></span><span>POR SEMANA <b>+${cash(item.weeklyIncome)}</b></span></div><div class="brand-item"><i aria-hidden="true">${escape(item.item.icon)}</i><span>ACESSÓRIO VIRTUAL<b>${escape(item.item.name)}</b></span></div><button data-action="sign-sponsor" data-id="${item.id}" ${blocked?'disabled':''}>${active?'PARCERIA ATIVA':brand?'AGUARDE O CONTRATO':state.week>14?'TEMPORADA ENCERRADA':'ASSINAR PARCERIA ↗'}</button></article>`}).join('')}</div>
  </section>
  <section class="sponsor-section"><div class="sponsor-section-head"><div><small class="eyebrow">03 / COSMÉTICOS</small><h2>Acessórios do clube</h2><p>Equipe um acessório recebido dos patrocinadores. Ele aparece no uniforme, sem alterar a força do time.</p></div></div><div class="sponsor-inventory">${state.sponsorItems?.length?state.sponsorItems.map(id=>{const item=BRANDS.find(entry=>entry.id===id);if(!item)return '';const selected=state.equippedSponsorItem===id;return `<button data-action="equip-sponsor-item" data-id="${id}" class="sponsor-inventory-item ${selected?'equipped':''}" aria-pressed="${selected}"><span aria-hidden="true">${escape(item.item.icon)}</span><b>${escape(item.item.name)}</b><small>${selected?'EQUIPADO':'EQUIPAR'}</small></button>`}).join(''):'<p>Assine uma parceria para desbloquear seu primeiro acessório.</p>'}</div></section>
  <p class="sponsor-disclaimer">Contratos, receitas, ganhos de torcida, marcas e acessórios são fictícios. Criadores reais aparecem como personagens de uma simulação, sem indicar parceria ou endosso.</p>`;
}
