import type {CareerState,Team} from '../types/career.ts';
import {calendarFixture,careerDate,dateKey,DAY_ACTIVITIES} from '../game/calendar.ts';

export function teamCalendar(state:CareerState,teams:Team[],month:Date,selected:string,esc:(value:unknown)=>string):string{
  const today=dateKey(careerDate(state.week,state.day||1));
  const first=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth(),1));
  const start=new Date(first);start.setUTCDate(1-(first.getUTCDay()+6)%7);
  const cells=Array.from({length:42},(_,i)=>{const date=new Date(start);date.setUTCDate(start.getUTCDate()+i);const key=dateKey(date),fixture=calendarFixture(state,teams,date);
    return `<button class="month-day ${date.getUTCMonth()!==first.getUTCMonth()?'outside':''} ${key===today?'today':''} ${key===selected?'selected':''} ${fixture?'fixture':''}" data-calendar-date="${key}" aria-label="${esc(date.toLocaleDateString('pt-BR',{timeZone:'UTC'}))}${fixture?` · ${esc(fixture.round.name)}`:''}" aria-pressed="${key===selected}"><span>${date.getUTCDate()}${key===today?'<i>HOJE</i>':''}</span>${fixture?`<b>${fixture.pending?'Convite':fixture.result?esc(fixture.result.score):`vs ${esc(fixture.opponent?.tag||'TBD')}`}</b><small>${esc(fixture.round.name)}</small>`:''}</button>`;
  });
  const date=new Date(`${selected}T00:00:00Z`),fixture=calendarFixture(state,teams,date);
  const active=date>=careerDate(1)&&date<=careerDate(14,7),future=selected>today;
  const title=fixture?fixture.round.name:future?'Agenda em aberto':active?DAY_ACTIVITIES[(date.getUTCDay()+6)%7]:'Sem compromissos';
  return `<section class="team-calendar"><header><div><small class="eyebrow">AGENDA DO ${esc(teams.find(t=>t.id===state.team)?.tag)}</small><h2>Calendário do time</h2></div><div class="month-navigation"><button data-calendar-month="-1" aria-label="Mês anterior">‹</button><b>${esc(first.toLocaleDateString('pt-BR',{month:'long',year:'numeric',timeZone:'UTC'}))}</b><button data-calendar-month="1" aria-label="Próximo mês">›</button><button data-calendar-today>Hoje</button></div></header><div class="team-calendar-body"><div><div class="month-weekdays">${['SEG','TER','QUA','QUI','SEX','SÁB','DOM'].map(d=>`<span>${d}</span>`).join('')}</div><div class="month-grid">${cells.join('')}</div><footer><span><i></i> Jogo / convite</span><span>Novas etapas aparecem ao avançar a temporada</span></footer></div><aside class="calendar-detail"><small>${esc(date.toLocaleDateString('pt-BR',{weekday:'long',timeZone:'UTC'}))}</small><strong>${date.getUTCDate()}<em>${esc(date.toLocaleDateString('pt-BR',{month:'long',timeZone:'UTC'}))}</em></strong><span class="calendar-detail-tag">${fixture?fixture.pending?'CONVITE PENDENTE':fixture.result?fixture.result.win?'VITÓRIA':'DERROTA':'DIA DE JOGO':'ROTINA DO CLUBE'}</span><h3>${esc(title)}</h3><p>${fixture?`${esc(fixture.round.phase)} · melhor de 3`:future?'Os jogos são confirmados conforme os convites e as classificações.':active?'Acompanhe o desenvolvimento do elenco e prepare sua próxima série.':'Selecione uma data da temporada.'}</p>${fixture?`<div class="calendar-versus"><b>${esc(teams.find(t=>t.id===state.team)?.tag)}</b><span>VS</span><b>${fixture.pending?'A confirmar':esc(fixture.opponent?.tag||'TBD')}</b></div><button data-view="competition">VER CAMPEONATO →</button>`:''}</aside></div></section>`;
}
