import abilities from '../../abilities.json';
import agents from '../../agents.json';
import {timedScore, aimScore, trainingLabels, type TrainingKind, type TrainingResult} from '../game/training.ts';
type Ability = typeof abilities[number];
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const shuffle=<T>(items:T[]):T[]=>{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;};
export function openTrainingSession(kind:TrainingKind,targets:TrainingResult['targets'],map:string,maps:string[],onComplete:(r:TrainingResult)=>string[]) {
 const previous=document.activeElement as HTMLElement|null,overlay=document.createElement('div');overlay.className='lab-overlay';document.body.append(overlay);
 const id=crypto.randomUUID();let started=0,elapsedMs=0,finished=false,disposed=false,timer:ReturnType<typeof setInterval>|undefined;
 overlay.innerHTML=`<section class="lab-dialog" role="dialog" aria-modal="true" aria-label="${trainingLabels[kind]}" tabindex="-1"><header><div><small>PERFORMANCE LAB</small><h2>${trainingLabels[kind]}</h2></div><button data-exit>Sair do treino</button></header><div class="lab-game"></div></section>`;
 const game=overlay.querySelector<HTMLElement>('.lab-game')!;
 const close=()=>{disposed=true;clearInterval(timer);document.removeEventListener('visibilitychange',visibility);overlay.remove();previous?.isConnected&&previous.focus();};
 overlay.querySelector<HTMLButtonElement>('[data-exit]')!.onclick=close;
 overlay.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const buttons=[...overlay.querySelectorAll<HTMLElement>('button:not(:disabled)')];const i=buttons.indexOf(document.activeElement as HTMLElement);e.preventDefault();buttons[(i+(e.shiftKey?-1:1)+buttons.length)%buttons.length]?.focus();}});
 function complete(accuracyScore:number,detail:string){const durationMs=kind==='aim'?elapsedMs:performance.now()-started,score=timedScore(accuracyScore,durationMs,kind==='aim'?60000:kind==='map-guess'?120000:180000);if(finished||disposed)return;finished=true;clearInterval(timer);const rewards=onComplete({id,kind,score,durationMs,accuracyScore,targets,map,completedAt:new Date().toISOString()});game.innerHTML=`<div class="lab-result"><small>SESSÃO CONCLUÍDA</small><strong>${score}<em>/100</em></strong><h3>${score>=75?'Excelente treino!':score>=40?'Bom começo. Continue treinando.':'Treino concluído. Tente novamente!'}</h3><p>${detail}</p><p>Tempo: ${(durationMs/1000).toFixed(1)}s · precisão: ${accuracyScore}/100 · fator de velocidade: ${(score/Math.max(1,accuracyScore)*100).toFixed(0)}%</p><div>${rewards.map(r=>`<p>${esc(r)}</p>`).join('')}</div><small>Domínio salvo na carreira · máximo 100%</small><button class="primary" data-finish>VOLTAR AOS TREINOS</button></div>`;game.querySelector<HTMLButtonElement>('[data-finish]')!.onclick=close;game.querySelector<HTMLButtonElement>('button')!.focus();}
 let paused=false;function visibility(){if(document.hidden&&kind==='aim'&&!finished){paused=true;const b=game.querySelector<HTMLButtonElement>('[data-pause]');if(b)b.textContent='RETOMAR';}}document.addEventListener('visibilitychange',visibility);
 function aim(){let hits=0,misses=0,remaining=30000,last=performance.now();
 game.innerHTML=`<div class="lab-metrics"><span>TEMPO <b data-time>30.0s</b></span><span>ACERTOS <b data-hits>0</b></span><span>PRECISÃO <b data-accuracy>100%</b></span><button data-pause>PAUSAR</button></div><p>Acerte os três alvos. Toques fora dos alvos contam como erros. Complete 30 acertos antes do limite: quanto mais rápido e preciso, mais pontos.</p><div class="aim-field" aria-label="Área de treino de mira"></div>`;
 const field=game.querySelector<HTMLElement>('.aim-field')!,update=()=>{game.querySelector('[data-hits]')!.textContent=String(hits);game.querySelector('[data-accuracy]')!.textContent=`${Math.round(hits/Math.max(1,hits+misses)*100)}%`;};
 function move(b:HTMLElement){let x=50,y=50;for(let attempt=0;attempt<40;attempt++){x=8+Math.random()*84;y=10+Math.random()*80;const clear=[...field.querySelectorAll<HTMLElement>('.aim-target')].filter(other=>other!==b).every(other=>Math.hypot((x-parseFloat(other.style.left))*field.clientWidth/100,(y-parseFloat(other.style.top))*field.clientHeight/100)>75);if(clear)break;}b.style.left=`${x}%`;b.style.top=`${y}%`;}
 for(let i=0;i<3;i++){const b=document.createElement('button');b.className='aim-target';b.setAttribute('aria-label',`Alvo ${i+1}`);move(b);b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();if(paused||finished)return;hits++;move(b);update();if(hits>=30){elapsedMs=30000-remaining;complete(aimScore(hits,misses),`${hits} acertos · ${misses} erros`);}};b.onclick=e=>{if(e.detail===0&&!paused&&!finished){hits++;move(b);update();if(hits>=30){elapsedMs=30000-remaining;complete(aimScore(hits,misses),`${hits} acertos · ${misses} erros`);}}};field.append(b);}
 field.onpointerdown=()=>{if(!paused&&!finished){misses++;update();}};
 game.querySelector<HTMLButtonElement>('[data-pause]')!.onclick=e=>{paused=!paused;last=performance.now();(e.currentTarget as HTMLElement).textContent=paused?'RETOMAR':'PAUSAR';};
 timer=setInterval(()=>{const now=performance.now();if(!paused)remaining=Math.max(0,remaining-(now-last));last=now;elapsedMs=30000-remaining;game.querySelector('[data-time]')!.textContent=`${(remaining/1000).toFixed(1)}s`;if(remaining<=0)complete(aimScore(hits,misses),`${hits} acertos · ${misses} erros · precisão ${Math.round(hits/Math.max(1,hits+misses)*100)}%`);},50);
 }
 function matching(){let board=0,firstCorrect=0,left:string|null=null;const assigned=[...new Set(targets.map(t=>t.agentId))];
 function next(){if(board===3){complete(Math.round(firstCorrect/12*100),`${firstCorrect} de 12 conexões corretas na primeira tentativa.`);return;}
 let picks:Ability[];
 if(kind==='agent-match'){const ids=shuffle([...assigned,...shuffle(agents.map(a=>a.id).filter(a=>!assigned.includes(a)))].slice(0,4));picks=ids.map(id=>shuffle(abilities.filter(a=>a.agentId===id))[0]);}
 else {const pool=shuffle(abilities.filter(a=>assigned.includes(a.agentId)));const unique=[...pool,...shuffle(abilities)].filter((a,i,all)=>all.findIndex(b=>b.name===a.name)===i);picks=unique.slice(0,4);}
 const matched=new Set<string>(),attempted=new Set<string>();
 game.innerHTML=`<div class="lab-metrics"><span>TEMPO <b data-elapsed>0.0s</b></span><span>RODADA <b>${board+1}/3</b></span><span>CONEXÕES <b data-progress>0/4</b></span></div><p>Selecione uma habilidade e depois ${kind==='agent-match'?'seu agente':'seu nome'}. A primeira tentativa define a pontuação.</p><div class="connect-board"><svg aria-hidden="true"></svg><div class="connect-column">${shuffle(picks).map(a=>`<button data-left="${a.id}" aria-label="Habilidade ${a.slot}"><img src="${a.icon}" alt="Ícone da habilidade"><small>${a.slot==='Ultimate'?'ULTIMATE':a.slot==='Grenade'?'HABILIDADE C':a.slot==='Ability1'?'HABILIDADE Q':'HABILIDADE E'}</small></button>`).join('')}</div><div class="connect-column">${shuffle(picks).map(a=>`<button data-right="${a.id}">${kind==='agent-match'?`<img src="/assets/agents/${a.agentId}.png" alt=""><b>${a.agentName}</b>`:`<b>${a.name}</b>`}</button>`).join('')}</div></div><p data-feedback role="status">Conecte os quatro pares.</p><button class="primary" data-next disabled>PRÓXIMA RODADA ↗</button>`;
 const feedback=game.querySelector<HTMLElement>('[data-feedback]')!;
 game.querySelectorAll<HTMLButtonElement>('[data-left]').forEach(b=>b.onclick=()=>{left=b.dataset.left!;game.querySelectorAll('[data-left]').forEach(x=>x.classList.remove('chosen'));b.classList.add('chosen');feedback.textContent='Agora selecione a correspondência à direita.';});
 game.querySelectorAll<HTMLButtonElement>('[data-right]').forEach(b=>b.onclick=()=>{if(!left){feedback.textContent='Selecione primeiro um ícone à esquerda.';return;}const key=left,first=!attempted.has(key);attempted.add(key);if(key!==b.dataset.right){feedback.textContent='Ainda não! Tente outra correspondência. Este par não pontua mais.';return;}if(first)firstCorrect++;matched.add(key);const a=game.querySelector<HTMLButtonElement>(`[data-left="${key}"]`)!;a.disabled=true;b.disabled=true;a.classList.add('connected');b.classList.add('connected');const svg=game.querySelector('svg')!,box=svg.getBoundingClientRect(),ab=a.getBoundingClientRect(),bb=b.getBoundingClientRect();const line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [attr,value] of Object.entries({x1:ab.right-box.left,y1:ab.top+ab.height/2-box.top,x2:bb.left-box.left,y2:bb.top+bb.height/2-box.top}))line.setAttribute(attr,`${value/(attr.startsWith('x')?box.width:box.height)*100}%`);svg.append(line);left=null;game.querySelector('[data-progress]')!.textContent=`${matched.size}/4`;const ability=picks.find(p=>p.id===key)!;feedback.textContent=`Correto: ${ability.name} → ${ability.agentName}.`;if(matched.size===4)game.querySelector<HTMLButtonElement>('[data-next]')!.disabled=false;});
 game.querySelector<HTMLButtonElement>('[data-next]')!.onclick=()=>{board++;next();};left=null;
 }next();}
 function guessing(){const rounds=shuffle([map,...shuffle(maps.filter(m=>m!==map)).slice(0,5)]);let round=0,correct=0;
 function next(){if(round===rounds.length){complete(Math.round(correct/rounds.length*100),`${correct} de ${rounds.length} mapas identificados · evolução em ${map}.`);return;}const answer=rounds[round],options=shuffle([answer,...shuffle(maps.filter(m=>m!==answer)).slice(0,3)]);
 game.innerHTML=`<div class="lab-metrics"><span>TEMPO <b data-elapsed>0.0s</b></span><span>MAPA <b>${round+1}/${rounds.length}</b></span><span>ACERTOS <b>${correct}</b></span></div><p>De qual mapa é este recorte? Observe a arquitetura e o cenário.</p><canvas class="map-crop" width="600" height="330" aria-label="Recorte de um mapa"></canvas><p data-feedback role="status">Carregando cenário…</p><div class="map-answers">${options.map(m=>`<button data-answer="${m}" disabled>${m}</button>`).join('')}</div><button class="primary" data-next hidden>PRÓXIMO MAPA ↗</button>`;
 const img=new Image(),canvas=game.querySelector<HTMLCanvasElement>('canvas')!,feedback=game.querySelector<HTMLElement>('[data-feedback]')!;
 img.onload=()=>{if(disposed||!canvas.isConnected)return;const w=img.width*.4,h=w*330/600,x=Math.random()*(img.width-w),y=Math.random()*Math.max(0,img.height-h);canvas.getContext('2d')!.drawImage(img,x,y,w,h,0,0,600,330);feedback.textContent='Escolha uma resposta.';game.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(b=>b.disabled=false);};
 img.onerror=()=>{if(!canvas.isConnected)return;feedback.innerHTML='Não foi possível carregar o cenário. <button data-retry>Tentar novamente</button>';feedback.querySelector<HTMLButtonElement>('button')!.onclick=()=>{img.src=`/assets/maps/${answer.toLowerCase()}-splash.jpg?retry=${Date.now()}`;};};img.src=`/assets/maps/${answer.toLowerCase()}-splash.jpg`;
 game.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(b=>b.onclick=()=>{if(b.dataset.answer===answer)correct++;game.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(x=>{x.disabled=true;x.classList.toggle('connected',x.dataset.answer===answer);x.classList.toggle('incorrect',x===b&&x.dataset.answer!==answer);});canvas.getContext('2d')!.drawImage(img,0,0,img.width,img.height,0,0,600,330);feedback.textContent=`${b.dataset.answer===answer?'Correto!':'Resposta incorreta.'} Este mapa é ${answer}.`;game.querySelector<HTMLButtonElement>('[data-next]')!.hidden=false;});game.querySelector<HTMLButtonElement>('[data-next]')!.onclick=()=>{round++;next();};
 }next();}
 game.innerHTML=`<div class="lab-intro"><span class="lab-crosshair">⌖</span><h3>${targets.length} atleta(s) em treinamento</h3><p>${kind==='aim'?'30 segundos. Acerte os alvos com rapidez e precisão.':kind==='map-guess'?'6 recortes. Cada resposta correta vale pontos.':'3 rodadas de 4 pares. Conecte os pares certos na primeira tentativa.'}</p><p>Quanto mais rápido você concluir com acertos, mais pontos. Recompensa: de 0 a 8 pontos de domínio, conforme sua pontuação.</p><button class="primary" data-begin>COMEÇAR</button></div>`;
 game.querySelector<HTMLButtonElement>('[data-begin]')!.onclick=()=>{started=performance.now();if(kind!=='aim')timer=setInterval(()=>{const label=game.querySelector('[data-elapsed]');if(label)label.textContent=`${((performance.now()-started)/1000).toFixed(1)}s`;},100);if(kind==='aim')aim();else if(kind==='map-guess')guessing();else matching();};overlay.querySelector<HTMLButtonElement>('[data-begin]')!.focus();
}
